[package]
name = "message-hub"
version = "0.1.0"
edition = "2021"
workspace.resolver = 2
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "*"
futures = "0.1.17"
actix-web = "4.4.0"
log = "*"
chrono = "0.4"
url = "*"
serde_json = "*"
serde = "*"
serde_derive = "*"
rust-crypto = "^0.2"
rkv = "0.10"
config = "0.9"
lazy_static = "*"
clap = "~2.33"
reqwest = "0.9.16"
quick-xml = "0.12.0"
uuid = { version = "0.7", features = ["v4"] }
sha1_smol = "1.0.0"
base64 = "0.21.4"
aes = "0.7.5"
block-modes = "0.8.1"
actix-files = "0.6.2"
handlebars = { version = "4.4.0", features = ["dir_source"] }
rbs = "4.4.0"
rbatis = "4.4.1"
rbdc-mysql = "4.4.0"
state = "0.6.0"
