[package]
name = "message-hub"
version = "0.1.1"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
application-beans = { git = "https://github.com/caijh/application-rs.git" }
application-core = { git = "https://github.com/caijh/application-rs.git" }
application-context = { git = "https://github.com/caijh/application-rs.git" }
application-web = { git = "https://github.com/caijh/application-rs.git" }
application-web-macros = { git = "https://github.com/caijh/application-rs.git" }
application-web-actuator = { git = "https://github.com/caijh/application-rs.git" }
application-boot = { git = "https://github.com/caijh/application-rs.git" }

util = { git = "https://caijh@bitbucket.org/bytebinary/util-rs.git" }
database-common = { git = "https://caijh@bitbucket.org/bytebinary/database-common-rs.git" }
database-mysql-seaorm = { git = "https://caijh@bitbucket.org/bytebinary/database-mysql-seaorm-rs.git" }
sea-orm = { version = "1.0.1", features = ["sqlx-mysql", "runtime-tokio-rustls", "macros", "with-bigdecimal", "with-uuid", "with-json", "with-chrono", "with-time"] }
# redis
redis = { version = "0.24.0", features = ["tls-rustls"] }
redis-io = { git = "https://caijh@bitbucket.org/bytebinary/redis-io-rs.git" }

futures = "0.3.30"
chrono = "0.4"
rust-crypto = "^0.2"
config = "0.14.0"
clap = { version = "4.5.18", features = ["derive", "cargo"] }
reqwest = { version = "0.12.7", features = ["json"] }
quick-xml = "0.36.2"
uuid = { version = "1.10.0", features = ["v4"] }
sha1_smol = "1.0.1"
base64 = "0.22.1"
aes = "0.8.4"
state = "0.6.0"
serde = "1.0.210"
serde_derive = "1.0.210"
serde_json = "1.0.128"
env_logger = "0.11.5"
lazy_static = "1.5.0"
url = "2.5.2"
parking_lot = "0.12.3"
tracing = "0.1.40"
cbc = { version = "0.1.2", features = ["alloc"] }
tokio = { version = "1.40.0", features = ["full"] }
axum = "0.7.6"
async-trait = "0.1.82"
askama = "0.11"
