[package]
name = "message-hub"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = {git = "https://caijh@bitbucket.org/bytebinary/util_rs.git"}
configuration= {git = "https://caijh@bitbucket.org/bytebinary/configuration_rs.git"}
registration = {git = "https://caijh@bitbucket.org/bytebinary/registration_rs.git"}
database = {git = "https://caijh@bitbucket.org/bytebinary/database_rs.git"}
futures = "0.3.28"
actix-web = "4.4.0"
chrono = "0.4"
rust-crypto = "^0.2"
rkv = "0.18.4"
config = "0.13.3"
clap = { version = "4.4.6", features = ["derive", "cargo"] }
reqwest = { version = "0.11.20", features = ["json"] }
quick-xml = "0.30.0"
uuid = { version = "1.4.1", features = ["v4"] }
sha1_smol = "1.0.0"
base64 = "0.21.4"
aes = "0.7.5"
block-modes = "0.8.1"
actix-files = "0.6.2"
handlebars = { version = "4.4.0", features = ["dir_source"] }
rbs = "4.4.0"
rbatis = "4.4.1"
rbdc-mysql = "4.4.0"
state = "0.6.0"
serde = "1.0.188"
serde_derive = "1.0.188"
serde_json = "1.0.107"
env_logger = "0.10.0"
lazy_static = "1.4.0"
log = "0.4.20"
url = "2.4.1"
parking_lot = "0.12.1"
