# 企业微信地址
[wxcorp]
id = ""
secret = ""
app_id = ""
token = ""
encoding_aes_key = ""

[server]
domain = "message.joinspace.pp.ua"

[database]
kind = "mysql"
host = "127.0.0.1"
port = 3306
user = "root"
password = "123456"
name = "messages"

[redis]
host = "127.0.0.1"
port = 6379
user = "default"
password = "redis"
